-- Drop all legacy CHECK constraints on expense_request left over from Spring Boot/Hibernate.
-- These were generated by Hibernate DDL and only allow the original enum values.
-- All columns now use proper PostgreSQL enum types which enforce valid values directly.
ALTER TABLE "expense_request" DROP CONSTRAINT IF EXISTS "expense_request_status_check";
ALTER TABLE "expense_request" DROP CONSTRAINT IF EXISTS "expense_request_vat_status_check";
ALTER TABLE "expense_request" DROP CONSTRAINT IF EXISTS "expense_request_request_type_check";
ALTER TABLE "expense_request" DROP CONSTRAINT IF EXISTS "expense_request_source_check";
ALTER TABLE "expense_request" DROP CONSTRAINT IF EXISTS "expense_request_refund_method_check";
